---
- hosts: server
  user: vagrant
  sudo: True
  roles: 
    - { role: common }
    - { role: database }
    - { role: mq }
    - { role: keystone }
    - { role: glance }
    - { role: nova-controller }
    - { role: neutron-controller }
    - { role: dashboard }
    - { role: nova-compute }
    - { role: neutron-compute }
    - { role: neutron-network }
