---
- name: install keystone packages
  apt: name={{ item }} state=present force=yes 
  with_items:
    - keystone
    - apache2
    - libapache2-mod-wsgi
    - memcached
    - python-memcache

- name: install openstack-client
  apt: name=python-openstackclient state=present force=yes

- name: update keystone conf
  template: src=keystone.conf dest=/etc/keystone/keystone.conf backup=yes
  notify: restart keystone

- name: update apache2 conf
  template: src=apache2.conf dest=/etc/apache2/apache2.conf backup=yes

- name: create wsgi-keystone conf
  template: src=wsgi-keystone.conf dest=/etc/apache2/sites-available/wsgi-keystone.conf backup=yes

- name: change owner
  file: path=/etc/apache2/sites-available/wsgi-keystone.conf owner=root group=root mode=0644
- name: link wsgi-keystone conf
  file: src=/etc/apache2/sites-available/wsgi-keystone.conf dest=/etc/apache2/sites-enabled state=link force=yes 

- name: delete sqlite database
  shell: rm /var/lib/keystone/keystone.db || echo sqllite database already removed

- name: manually stop keystone once
  service: name=keystone state=stopped

- name: keystone-manage db-sync
  shell: su -s /bin/sh -c "keystone-manage db_sync"

- name: cron job to purge expired tokens hourly
  shell: (crontab -l -u keystone 2>&1 | grep -q token_flush) || echo '@hourly /usr/bin/keystone-manage token_flush > /var/log/keystone/keystone-tokenflush.log 2>&1' >> /var/spool/cron/crontabs/keystone

- name: manually start keystone
  service: name=keystone state=started

- name: place keystone init script under /opt/
  template: src=keystone_init dest=/opt/keystone_init mode=0744

- name: run keystone_init
  shell: /opt/keystone_init #&& touch keystone_init_complete || keystone_init_failed
#  args:
#    creates: keystone_init_complete 

- name: keystone source files
  template: src={{ item }} dest=/opt/{{ item }}
  with_items:
    - admin-openrc.sh
    - demo-openrc.sh

- name: place service init script under /opt/
  template: src=service_init dest=/opt/service_init mode=0755

- name: set mode
  shell: chmod 655 /opt/admin-openrc.sh

- name: set environment
  shell: /opt/admin-openrc.sh

- name: register services
  shell: /opt/service_init #&& touch service_init_complete || service_init_failed
  #args:
    #creates: service_init_complete
